import QueryProvider from '@/lib/providers/QueryProvider'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { App as AntdApp, ConfigProvider } from 'antd'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren, Suspense } from 'react'
import { violet } from 'tailwindcss/colors'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryProvider>
          <Suspense fallback={null}>
            <AntdRegistry>
              <ConfigProvider theme={{ token: { colorPrimary: violet[500] } }}>
                <AntdApp>{props.children}</AntdApp>
              </ConfigProvider>
            </AntdRegistry>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  )
}
