import QueryProvider from '@/lib/providers/QueryProvider'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider } from 'antd'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import { violet } from 'tailwindcss/colors'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryProvider>
          <Suspense fallback={null}>
            <AntdRegistry>
              <ConfigProvider theme={{ token: { colorPrimary: violet[500] } }}>{children}</ConfigProvider>
            </AntdRegistry>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  )
}
